// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxtl_GkawgyqqsfBo3TNmHVpFXernrvPo',
    appId: '1:1007150715053:web:512a9d67eb4c7bf42cb624',
    messagingSenderId: '1007150715053',
    projectId: 'mynotes-fluttervinu',
    authDomain: 'mynotes-fluttervinu.firebaseapp.com',
    storageBucket: 'mynotes-fluttervinu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6wjVHYTSyWFOWTQJw6Mee653XL7V9eWk',
    appId: '1:1007150715053:android:ddea085ecbc68c7d2cb624',
    messagingSenderId: '1007150715053',
    projectId: 'mynotes-fluttervinu',
    storageBucket: 'mynotes-fluttervinu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGdsME3euIK4SCYcwhJyx2s-MhaIPNAQc',
    appId: '1:1007150715053:ios:581767b65665b7072cb624',
    messagingSenderId: '1007150715053',
    projectId: 'mynotes-fluttervinu',
    storageBucket: 'mynotes-fluttervinu.appspot.com',
    iosClientId:
        '1007150715053-tvr0nh7ohmfh5ti744culcl7sf9236vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGdsME3euIK4SCYcwhJyx2s-MhaIPNAQc',
    appId: '1:1007150715053:ios:581767b65665b7072cb624',
    messagingSenderId: '1007150715053',
    projectId: 'mynotes-fluttervinu',
    storageBucket: 'mynotes-fluttervinu.appspot.com',
    iosClientId:
        '1007150715053-tvr0nh7ohmfh5ti744culcl7sf9236vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
